// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/datacatalog/v1/data_source.proto

package com.google.cloud.datacatalog.v1;

public interface DataSourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.datacatalog.v1.DataSource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Service in which the data is physically stored.
   * </pre>
   *
   * <code>.google.cloud.datacatalog.v1.DataSource.Service service = 1;</code>
   * @return The enum numeric value on the wire for service.
   */
  int getServiceValue();
  /**
   * <pre>
   * Service in which the data is physically stored.
   * </pre>
   *
   * <code>.google.cloud.datacatalog.v1.DataSource.Service service = 1;</code>
   * @return The service.
   */
  com.google.cloud.datacatalog.v1.DataSource.Service getService();

  /**
   * <pre>
   * Full name of the resource as defined by the service, e.g.
   * //bigquery.googleapis.com/projects/{project_id}/locations/{location}/datasets/{dataset_id}/tables/{table_id}
   * </pre>
   *
   * <code>string resource = 2;</code>
   * @return The resource.
   */
  java.lang.String getResource();
  /**
   * <pre>
   * Full name of the resource as defined by the service, e.g.
   * //bigquery.googleapis.com/projects/{project_id}/locations/{location}/datasets/{dataset_id}/tables/{table_id}
   * </pre>
   *
   * <code>string resource = 2;</code>
   * @return The bytes for resource.
   */
  com.google.protobuf.ByteString
      getResourceBytes();
}
